### ISSUE TITLE
能否支持iconfont？

### ISSUE THREAD

**Issue by gafish** [semipx/yesicon-forum#11]
我在Flutter中通过iconfont的方式使用图标，目前是在iconfont.cn上添加图标并下载字体文件，yesicon是否有支持iconfont的计划呢？

**Comment by dongnaebi** [comment]
恐怕不行，iconfont 图标数据是拿不到的。好像 Flutter 也有个 SVG 的库，推荐使用 SVG 吧

**Comment by gafish** [comment]
也可以，下次我换svg图标使用，或者下载图标后上传到iconfont.cn去转换一下使用
