### ISSUE TITLE
给 safari 网页加上 ico

### ISSUE THREAD

**Issue by Amnesiash** [semipx/yesicon-forum#12]
<img width="1274" alt="Snipaste_2024-01-23_11-41-02" src="https://github.com/rotick/yesicon-forum/assets/44333360/3f4a306a-5fee-4e5d-a9b6-14191c9196ea">
<img width="475" alt="Snipaste_2024-01-23_11-40-35" src="https://github.com/rotick/yesicon-forum/assets/44333360/f69dddd7-8d57-43f6-838c-2b800074c77c">

**Comment by dongnaebi** [comment]
好的，我回头看看为什么没出来

**Comment by dongnaebi** [comment]
修复了，删除下缓存就可以出来了
