### ISSUE TITLE
考虑缓存图标数据到浏览器，而不是加载时网络请求

### ISSUE THREAD

**Issue by hyoban** [semipx/yesicon-forum#15]
作为目前情况对比

![](https://s2.loli.net/2024/02/23/2sOlai16UkHb7hj.gif)

![](https://s2.loli.net/2024/02/23/xfNTKVI2ajmhJQk.gif)

**Comment by dongnaebi** [comment]
这里其实只有三个小图标是懒加载的，而列表是加了 `content-visibility: auto` 来提升首屏加载速度，但看你的录屏很奇怪，为什么这么久才出来，在我电脑上没有滚动到就出来了，等我研究一下看看

**Comment by Amnesiash** [comment]
我也是仅加载一部分，后续的都很慢

**Comment by dongnaebi** [comment]
这周末的版本我先把 content-visibility 去掉吧，没什么头绪

**Comment by dongnaebi** [comment]
我已经把 content-visibility 去掉了，你们再看看有没有好一些。

图标懒加载是一个特性来着，目的是每次都能看到不同的图标示例，就先保留这个特性了

**Comment by hyoban** [comment]
![](https://s2.loli.net/2024/03/02/VkwgKIQAqjzLORH.gif)

**Comment by dongnaebi** [comment]
我找到电脑复现了，是 backdrop-filter 的原因，这个太耗性能了😅已修复！
