### ISSUE TITLE
图标搜索很慢 甚至无响应

### ISSUE THREAD

**Issue by yuan746x** [semipx/yesicon-forum#16]
图标搜索很慢 甚至无响应

**Comment by dongnaebi** [comment]
Yesicon 目前正在遭受 DDOS 攻击，我正在想办法

**Comment by yuan746x** [comment]
all right




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月20日(星期三) 中午11:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rotick/yesicon-forum] 图标搜索很慢 甚至无响应 (Issue #16)





 
Yesicon 目前正在遭受 DDOS 攻击，我正在想办法
