### ISSUE TITLE
弹窗的打开和关闭有点慢

### ISSUE THREAD

**Issue by zhukaiqiang1** [semipx/yesicon-forum#18]
希望可以优化

**Comment by dongnaebi** [comment]
请提供更多的信息，如果可以麻烦录个屏

**Comment by zhukaiqiang1** [comment]
有个延迟
https://github.com/rotick/yesicon-forum/assets/35193643/78c486c8-d639-4e17-a47e-b61e6d04d601

**Comment by dongnaebi** [comment]
😯这一小点动画延迟都接受不了么

**Comment by zhukaiqiang1** [comment]
哈哈 最后还是优化了😂，现在快了很多
