### ISSUE TITLE
支持批量下载图标

### ISSUE THREAD

**Issue by Maxorao** [semipx/yesicon-forum#7]
每次下载图标都要一个一个下载，能否支持复选图标然后批量下载特定格式

**Comment by dongnaebi** [comment]
好的，麻烦可以描述一下你的使用场景吗？

希望直接在列表勾选，还是点开弹窗一个个去点呢？

勾选的时候，是期望可以选择多个收藏夹，还是直接一个购物车？

期待你能提供更多的建议，谢谢！

**Comment by Maxorao** [comment]
比如我搜索一个关键词，然后出来一个二维列表，我希望能够每个图标旁边都有一个复选框之类的东西（或者有一个复选模式的按钮可以唤出复选框），然后一键下载选中的图标组成的压缩包

**Comment by dongnaebi** [comment]
好的，等我后面研究一下怎么交互是最好的

**Comment by dongnaebi** [comment]
done, 欢迎体验并反馈

**Comment by Moyf** [comment]
请问这个功能就是现在的「图标盒子」吗？
有没有办法一键把所有搜索结果添加进当前盒子/新盒子里呢

**Comment by dongnaebi** [comment]
不是很理解你的使用场景是什么，为什么要下载所有搜索结果呢？搜索结果是分页加载的，也没法全部下载

**Comment by Moyf** [comment]
> 不是很理解你的使用场景是什么，为什么要下载所有搜索结果呢？搜索结果是分页加载的，也没法全部下载

![image](https://github.com/rotick/yesicon-forum/assets/4013062/eef7e34d-7214-424d-b69a-337b40fa7b72)
比较喜欢 Icons8 这个风格的图标，想要批量下载下来
（这样是不是太耗服务器资源了 🤔

**Comment by dongnaebi** [comment]
是不太好实现，可以自己本地写个脚本去将 iconify 的这个图标库的 json 文件转换成 svg，这样更简单些。

其实你下载了在电脑中还不好预览也不好搜索，不如要用到的时候就来 Yesicon 搜了复制或下载呢。
